# Generated by Django 6.0.6 on 2026-06-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_contact_message_statuses(apps, schema_editor):
    contact_message = apps.get_model("content", "ContactMessage")
    contact_message.objects.filter(status="reviewed").update(status="read")
    contact_message.objects.filter(status="contacted").update(status="replied")


def restore_contact_message_statuses(apps, schema_editor):
    contact_message = apps.get_model("content", "ContactMessage")
    contact_message.objects.filter(status="read").update(status="reviewed")
    contact_message.objects.filter(status="replied").update(status="contacted")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(migrate_contact_message_statuses, restore_contact_message_statuses),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده\u200cشده'), ('replied', 'پاسخ داده\u200cشده'), ('closed', 'بسته شده')], default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='ContactMessageInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_message_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='content.contactmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
