# Generated by Django 6.0.6 on 2026-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_code',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
