# Generated by Django 6.0.6 on 2026-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_customeraddress_customeroffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('order_manager', 'مدیر سفارش\u200cها'), ('product_manager', 'مدیر محصولات'), ('support', 'پشتیبانی')], default='', max_length=32),
        ),
    ]
