# Generated by Django 6.0.6 on 2026-06-25 09:31

import apps.core.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportattachment',
            name='file',
            field=models.FileField(upload_to='support-attachments/', validators=[apps.core.file_security.validate_customer_upload_file]),
        ),
    ]
