# Generated by Django 6.0.6 on 2026-06-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_status_changed', 'تغییر وضعیت سفارش'), ('product_price_changed', 'تغییر قیمت محصول'), ('product_inventory_changed', 'تغییر موجودی محصول'), ('product_deleted', 'حذف محصول'), ('sensitive_file_viewed', 'مشاهده فایل حساس'), ('sensitive_file_downloaded', 'دانلود فایل حساس'), ('design_request_replied', 'پاسخ به درخواست طراحی'), ('admin_access_changed', 'تغییر دسترسی مدیر')], db_index=True, max_length=64)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='admin_panel_entity__d94e57_idx'), models.Index(fields=['actor', 'created_at'], name='admin_panel_actor_i_766e15_idx')],
            },
        ),
    ]
