# Generated by Django 6.0.6 on 2026-07-01 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_orderinternalnote'),
        ('products', '0009_product_approved_reviews_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('hidden', 'مخفی')], db_index=True, default='pending', max_length=16)),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False)),
                ('is_reported', models.BooleanField(db_index=True, default=False)),
                ('admin_reply', models.TextField(blank=True, max_length=2000)),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reviews', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status', 'deleted_at'], name='reviews_rev_product_6608e5_idx'), models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_between_1_and_5'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('order_item__isnull', False)), fields=('user', 'order_item'), name='reviews_one_active_per_order_item'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('order_item__isnull', True)), fields=('user', 'product'), name='reviews_one_active_general_per_product')],
            },
        ),
    ]
