# Generated by Django 6.0.6 on 2026-06-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('IN_PERSON', 'پرداخت حضوری'), ('ONLINE_GATEWAY', 'پرداخت آنلاین'), ('BANK_TRANSFER', 'انتقال بانکی'), ('CASH_ON_DELIVERY', 'پرداخت هنگام تحویل')], max_length=24)),
                ('provider', models.CharField(choices=[('MANUAL', 'ثبت دستی'), ('GATEWAY', 'درگاه آنلاین'), ('BANK', 'بانک')], default='MANUAL', max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت\u200cشده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغوشده'), ('REFUNDED', 'بازپرداخت\u200cشده')], default='PENDING', max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
