# Generated by Django 6.0.6 on 2026-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_transactions_and_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
