# Generated by Django 6.0.6 on 2026-06-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_request', '0002_update_design_request_order_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='admin_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
