# Generated by Django 6.0.6 on 2026-06-25 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_request', '0003_designrequest_admin_response_and_more'),
        ('orders', '0008_orderinternalnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_requests', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('received', 'جدید'), ('reviewing', 'در حال بررسی'), ('needs_info', 'نیازمند اطلاعات بیشتر'), ('designing', 'در حال طراحی'), ('ready_for_approval', 'آماده تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده'), ('closed', 'بسته\u200cشده')], default='received', max_length=24),
        ),
        migrations.CreateModel(
            name='DesignRequestInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='design_request.designrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='design_request.designrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
