from django.urls import path

from .views import (
    AdminActivityLogListAPIView,
    AdminContactMessageBulkReadAPIView,
    AdminContactMessageDetailAPIView,
    AdminContactMessageInternalNoteDetailAPIView,
    AdminContactMessageInternalNoteListCreateAPIView,
    AdminContactMessageListAPIView,
    AdminContactMessageStatusUpdateAPIView,
    AdminCustomerDetailAPIView,
    AdminCustomerListAPIView,
    AdminDashboardAPIView,
    AdminCategoryDetailAPIView,
    AdminCategoryListCreateAPIView,
    AdminCustomerFileListAPIView,
    AdminCustomerFilePreviewAPIView,
    AdminCustomerFileServeAPIView,
    AdminMeAPIView,
    AdminManagerDetailAPIView,
    AdminManagerListCreateAPIView,
    AdminDesignRequestDetailAPIView,
    AdminDesignRequestInternalNoteDetailAPIView,
    AdminDesignRequestInternalNoteListCreateAPIView,
    AdminDesignRequestListAPIView,
    AdminDesignRequestOrderLinkAPIView,
    AdminDesignRequestResponseUpdateAPIView,
    AdminDesignRequestStatusHistoryAPIView,
    AdminDesignRequestStatusUpdateAPIView,
    AdminOrderDetailAPIView,
    AdminOrderCSVExportAPIView,
    AdminOrderInternalNoteDetailAPIView,
    AdminOrderInternalNoteListCreateAPIView,
    AdminOrderListAPIView,
    AdminOrderShippingUpdateAPIView,
    AdminOrderStatusHistoryAPIView,
    AdminOrderStatusUpdateAPIView,
    AdminProductCategoryListAPIView,
    AdminProductDetailAPIView,
    AdminProductInventoryHistoryAPIView,
    AdminProductImageDetailAPIView,
    AdminProductImageListCreateAPIView,
    AdminProductListCreateAPIView,
    AdminProductToggleActiveAPIView,
)

app_name = "admin_panel"

urlpatterns = [
    path("me/", AdminMeAPIView.as_view(), name="me"),
    path("settings/admin-users/", AdminManagerListCreateAPIView.as_view(), name="admin-users"),
    path("settings/admin-users/<int:pk>/", AdminManagerDetailAPIView.as_view(), name="admin-user-detail"),
    path("dashboard/", AdminDashboardAPIView.as_view(), name="dashboard"),
    path("activity-logs/", AdminActivityLogListAPIView.as_view(), name="activity-logs"),
    path("contact-messages/", AdminContactMessageListAPIView.as_view(), name="contact-messages"),
    path("contact-messages/bulk-read/", AdminContactMessageBulkReadAPIView.as_view(), name="contact-messages-bulk-read"),
    path("contact-messages/<int:pk>/", AdminContactMessageDetailAPIView.as_view(), name="contact-message-detail"),
    path("contact-messages/<int:pk>/status/", AdminContactMessageStatusUpdateAPIView.as_view(), name="contact-message-status"),
    path("contact-messages/<int:pk>/notes/", AdminContactMessageInternalNoteListCreateAPIView.as_view(), name="contact-message-notes"),
    path("contact-messages/<int:pk>/notes/<int:note_id>/", AdminContactMessageInternalNoteDetailAPIView.as_view(), name="contact-message-note-detail"),
    path("customers/", AdminCustomerListAPIView.as_view(), name="customers"),
    path("customers/<int:pk>/", AdminCustomerDetailAPIView.as_view(), name="customer-detail"),
    path("design-requests/", AdminDesignRequestListAPIView.as_view(), name="design-requests"),
    path("design-requests/<int:pk>/", AdminDesignRequestDetailAPIView.as_view(), name="design-request-detail"),
    path("design-requests/<int:pk>/status/", AdminDesignRequestStatusUpdateAPIView.as_view(), name="design-request-status"),
    path("design-requests/<int:pk>/response/", AdminDesignRequestResponseUpdateAPIView.as_view(), name="design-request-response"),
    path("design-requests/<int:pk>/reply/", AdminDesignRequestResponseUpdateAPIView.as_view(), name="design-request-reply"),
    path("design-requests/<int:pk>/order/", AdminDesignRequestOrderLinkAPIView.as_view(), name="design-request-order"),
    path("design-requests/<int:pk>/history/", AdminDesignRequestStatusHistoryAPIView.as_view(), name="design-request-history"),
    path("design-requests/<int:pk>/notes/", AdminDesignRequestInternalNoteListCreateAPIView.as_view(), name="design-request-notes"),
    path("design-requests/<int:pk>/notes/<int:note_id>/", AdminDesignRequestInternalNoteDetailAPIView.as_view(), name="design-request-note-detail"),
    path("customer-files/", AdminCustomerFileListAPIView.as_view(), name="customer-files"),
    path("customer-files/<str:source>/<int:pk>/download/", AdminCustomerFileServeAPIView.as_view(), name="customer-file-download"),
    path("customer-files/<str:source>/<int:pk>/preview/", AdminCustomerFilePreviewAPIView.as_view(), name="customer-file-preview"),
    path("categories/", AdminCategoryListCreateAPIView.as_view(), name="categories"),
    path("categories/<int:pk>/", AdminCategoryDetailAPIView.as_view(), name="category-detail"),
    path("orders/", AdminOrderListAPIView.as_view(), name="orders"),
    path("orders/export/csv/", AdminOrderCSVExportAPIView.as_view(), name="orders-export-csv"),
    path("orders/<int:pk>/", AdminOrderDetailAPIView.as_view(), name="order-detail"),
    path("orders/<int:pk>/history/", AdminOrderStatusHistoryAPIView.as_view(), name="order-history"),
    path("orders/<int:pk>/notes/", AdminOrderInternalNoteListCreateAPIView.as_view(), name="order-notes"),
    path("orders/<int:pk>/notes/<int:note_id>/", AdminOrderInternalNoteDetailAPIView.as_view(), name="order-note-detail"),
    path("orders/<int:pk>/status/", AdminOrderStatusUpdateAPIView.as_view(), name="order-status"),
    path("orders/<int:pk>/shipping/", AdminOrderShippingUpdateAPIView.as_view(), name="order-shipping"),
    path("products/", AdminProductListCreateAPIView.as_view(), name="products"),
    path("products/categories/", AdminProductCategoryListAPIView.as_view(), name="product-categories"),
    path("products/<int:pk>/", AdminProductDetailAPIView.as_view(), name="product-detail"),
    path("products/<int:pk>/toggle-active/", AdminProductToggleActiveAPIView.as_view(), name="product-toggle-active"),
    path("products/<int:pk>/images/", AdminProductImageListCreateAPIView.as_view(), name="product-images"),
    path("products/<int:pk>/images/<int:image_id>/", AdminProductImageDetailAPIView.as_view(), name="product-image-detail"),
    path("products/<int:pk>/inventory-history/", AdminProductInventoryHistoryAPIView.as_view(), name="product-inventory-history"),
]
