# Generated by Django 6.0.6 on 2026-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_backfill_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
